---
name: Release Production

on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: "Run in test mode without publishing artifacts"
        required: false
        default: false
        type: boolean
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

permissions:
  contents: read # Set default read-only permissions

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/test.yaml
    permissions:
      contents: read # For code checkout

  build:
    name: Run Build
    needs: [test]
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: write # For code checkout and publishing releases
      packages: write # For pushing images to registries
      attestations: write # For generating provenance and SBOMs
      id-token: write # For OIDC auth to GHCR
    with:
      ENVIRONMENT: CI-Release
      BUILD_TYPE: stable
      DRY_RUN: ${{ inputs.DRY_RUN || false }}

  update-go-docs:
    name: Run Go Pkg Update
    needs: [build]
    if: ${{ !inputs.DRY_RUN }}
    permissions:
      contents: read
    uses: ./.github/workflows/update-go-docs.yaml

  publish-docs:
    name: Publish Documentation
    needs: [build]
    if: ${{ !inputs.DRY_RUN }}
    runs-on: ubuntu-latest
    permissions:
      actions: write # For dispatching the docs workflow
      contents: read # For code checkout
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Trigger Docs Publication
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
        run: |
          gh workflow run publish-docs.yaml --ref master \
            -f VERSION="${VERSION}" \
            -f ALIASES="latest"
