---
name: Refresh pkg.go.dev

on:
  - workflow_dispatch
  - workflow_call

permissions:
  contents: read # Set default read-only permissions

jobs:
  update-go-docs:
    name: Update pkg.go.dev
    runs-on: ubuntu-latest
    steps:
      - name: Harden the Runner (Step Security)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Run pkg.go.dev Update
        uses: nicholas-fedor/go-proxy-pull-action@63778237b5a5aa2cf3c811234051363bf8eafd48 # v1.1.43
        with:
          goproxy: https://proxy.golang.org
          import_path: github.com/nicholas-fedor/watchtower
